Using Jimp instead of Paper.js
ben-eb/postcss-resemble-image pull request #3
Opened 2016-11-10 13:20 UTC by Lorti

These changes address #1. 

I replaced `asset-resolver`, `image-size` and `paper` with a single dependency to `jimp`. Wasn't able to get 100% test coverage though… any ideas on that?

2016-11-10 14:11 UTC, ben-eb commented
Hi @Lorti,

Thanks! This looks really good. I think we can address the code coverage by trying to load an unsupported image type; we could go with an obsoleted image format, or we could try to load some other binary format that Jimp doesn't support. Some small fixture in `/src/__tests__` would be good. What do you think?

2016-11-10 16:35 UTC, Lorti commented
Thanks, you were right about the format Jimp doesn't support. Now waiting for Travis to build 🙂

2016-11-10 17:25 UTC, ben-eb commented
Seems like Node 4 on OS X is still not playing ball. Perhaps we could simplify the Travis config further?

```yml
language: node_js
matrix:
  include:
    - node_js: '6'
      os: linux
    - node_js: '5'
      os: linux
    - node_js: '4'
      os: linux
    - node_js: '6'
      os: osx
    - node_js: '5'
      os: osx
    - node_js: '4'
      os: osx
```

We don't need either `sudo` or any extra dependencies as we removed Cairo.

2016-11-10 20:21 UTC, Lorti commented
I haven't had any experience with Travis prior to today, but it seems that it's been choking on the Node 4 even before my changes, taking as long as the other five builds combined. Not sure what do to right now.

2016-11-10 20:41 UTC, ben-eb commented
Yeah, it's been a bit problematic for me also, but I put this down to the extra hoops that I had to jump through to get Cairo running on CI. Could you try with the exact config that I posted in the last comment please? If we can't get it to pass I'll try contacting support and see if they know what's going on.

2016-11-10 23:44 UTC, ben-eb requested changes
Looks great so far! Just a few minor tweaks. 😄

2016-11-10 23:44 UTC, ben-eb commented on .travis.yml
> +    - node_js: '4'
Still problematic. I think we should remove the Node 4 tests for OS X, they take too long on Travis.

2016-11-10 23:44 UTC, ben-eb commented on src/__tests__/index.js
> +    `header{background:resemble-image(url("${unprocessable}"), twenty-five)}`
I think I would prefer that we tested this with an empty value for the fidelity, as the module also throws when the fidelity is incorrect. That way we can be sure that we are testing the invalid file and not an invalid fidelity.

2016-11-10 23:44 UTC, ben-eb commented on src/resembleImage.js
> +    return convert(r) + convert(g) + convert(b);
We need a leading `#` for this value; I used to have actual hex values in the tests but the values don't actually align across platforms. But we can update the tests to make sure that each stop is a hex colour of some sort:

```js
function assertColourStops (t, fixture, expected, options) {
    return postcss(plugin(options)).process(fixture).then((result) => {
        valueParser(result.root.first.nodes[0].value).walk(node => {
            if (node.value !== 'linear-gradient') {
                return false;
            }
            const stops = getArguments(node).slice(1);
            t.deepEqual(stops.length, expected);
            stops.forEach(stop => {
                const colour = stop[0].value;
                t.truthy(
                    colour.length === 7 && !isNaN(parseInt(colour.slice(1), 16))
                );
            });
        });
    });
}
```

2016-11-11 10:00 UTC, Lorti commented
I have opted to use the regular expression `/^#[0-9a-f]{6}$/i` instead of `colour.length === 7 && !isNaN(parseInt(colour.slice(1), 16))`. This way the test also looks for the '#' sign.

2016-11-11 17:11 UTC, ben-eb approved these changes

2016-11-11 17:16 UTC, ben-eb commented
Alright, thanks! 👍

2016-11-11 17:17 UTC, merged