Move fallback gradient output to the end
ben-eb/postcss-resemble-image pull request #9
Opened 2017-01-17 15:55 UTC by diagramatics

Fixes #8. Thanks for sorting out what to do to fix it really quickly!

I've also added a test, but we might need a test to check if the gradient is added at the end. I've also added another test to check if `resemble-image()` is removed in the output.

2017-01-17 20:40 UTC, ben-eb requested changes

2017-01-17 20:40 UTC, ben-eb commented on src/__tests__/index.js
> +    `header{background:resemble-image(url("${image}")) no-repeat center / cover}`,
Perhaps we want to test that the gradient makes it to the end of the value? Something like this:

```js
test('should handle background value shorthand', t => {
  const fixture = `header{background:resemble-image(url("${image}")) no-repeat center / cover}`;
  return postcss(plugin()).process(fixture).then((result) => {
    t.is(result.root.first.nodes[0].value.indexOf('linear-gradient'), 30); // replace with the actual index!
    return assertColourStops(t, fixture, 4);
  });
});

2017-01-17 23:45 UTC, diagramatics commented on src/__tests__/index.js
> +    `header{background:resemble-image(url("${image}")) no-repeat center / cover}`,
Seems like a regex is a more robust choice if we don't want to hardcode the index in the test. Updated with the next commit.

2017-01-18 12:35 UTC, ben-eb approved these changes

2017-01-18 12:35 UTC, merged

2017-01-18 12:38 UTC, ben-eb commented
Many thanks for your contribution! I've released this now as `2.1.1`. 👍

2017-01-18 13:14 UTC, diagramatics commented
Perfect! Looking forward to using this in a production site 🎉